name: Build Python EXE for Ubuntu, Windows, and MacOS

on:
  push:
    branches: [ main, siri,ubuntu]
  

jobs:
  build:
    name: build on matrix.os
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
     
      run: |
        pip install --upgrade pip
        pip install pytest black flake8 pylint pyinstaller
        pip install -r requirements.txt
       
        pyinstaller --version  # Verify

    - name: Build executable inter_sum.py
    
      run: |
       
        pyinstaller --onefile --noconfirm --clean inter_sum.py

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: executable for matrix.os
        path: |
           dist/inter_sum
           dist/inter_sum.exe
           dist/inter_sum.app
