name: Build ubuntu Binary

on:
  push:
    branches: [ main, siri,ubuntu ]
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
     
      run: |
        pip install --upgrade pip
        pip install pytest black flake8 pylint pyinstaller
        pip install -r requirements.txt
       
        pyinstaller --version  # Verify

    - name: Build executable tictactoe.py
    
      run: |
       
        pyinstaller --onefile --noconfirm --clean tictactoe.py

    - name: Upload ubuntu executable as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu-executable
        path: dist/tictactoe.exe
