name: Build Windows Binary

on:
  push:
    branches: [ main, siri]
  workflow_dispatch:  # allows manual trigger

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      shell: pwsh  # PowerShell explicit
      run: |
        pip install --upgrade pip
        pip install pytest black flake8 pylint pyinstaller
        pip install -r requirements.txt
       
        pyinstaller --version  # Verify

    - name: Build executable inter_sum.py
      shell: pwsh
      run: |
       
        pyinstaller --onefile --noconfirm --clean inter_sum.py

    - name: Upload EXE as artifact
      uses: actions/upload-artifact@v4
      with:
        name: python-exe
        path: dist/inter_sum.exe
